import ProgressBar from "@/components/ProgressBar";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Providers";
import "./globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Provider>
					<div className="flex flex-col md:flex-row w-full h-fit">
						<ProgressBar />
						<Navbar />
						{children}
					</div>
				</Provider>
			</body>
		</html>
	);
}
